name: learning-management-system
services:
    postgres:
        container_name: postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        image: postgres

    pgadmin4:
        container_name: pgadmin4
        ports:
            - 8080:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        image: dpage/pgadmin4
        depends_on:
            - postgres